server.port: 8080

giphy:
  feign:
    logger:
      enabled: true
  url.general: https://api.giphy.com/v1/gifs
  api.key:
  courseUp: rich
  courseDown: broke
openexchangerates:
  url.general: https://openexchangerates.org/api
  app.id:
  currency: USD
logging:
  level:
    ts.andrey.giphy:
      feign:
        CourseClient: DEBUG
        GiphyClient: DEBUG